train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: F:/Datasets/Certificate_Tamper_Dataset_Image/img/train
      root_path_2: F:/Datasets/Certificate_Tamper_Dataset_Image/annotation/train
      cache: none
      split_key: train
  wrapper:
    name: train
    args:
      inp_size: 1024
      augment: false
  batch_size: 4

data_size: 1024
DocAI: Layoutlmv3
DocAI_checkpoint: ./DocAI_pretrained/funsd
save_csv_path: ./csv/Certificate_Text_Tampering_Probs.csv
